// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TCU_FleaMarket.Data;

#nullable disable

namespace TCU_FleaMarket.Migrations
{
    [DbContext(typeof(UserDbContext))]
    partial class UserDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.5");

            modelBuilder.Entity("TCU_FleaMarket.Data.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Biography")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("Contact")
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("Image")
                        .HasColumnType("BLOB");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1200,
                            Biography = "bio1",
                            Name = "name1"
                        },
                        new
                        {
                            Id = 1201,
                            Biography = "bio2",
                            Name = "name2"
                        },
                        new
                        {
                            Id = 1202,
                            Biography = "bio3",
                            Name = "name3"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
