// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TCU_FleaMarket.Data;

#nullable disable

namespace TCU_FleaMarket.Migrations.ExhibitDb
{
    [DbContext(typeof(ExhibitDbContext))]
    [Migration("20220612063144_ExhibitDatabase")]
    partial class ExhibitDatabase
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.5");

            modelBuilder.Entity("TCU_FleaMarket.Data.Exhibit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int>("ExhibitorsId")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("Image")
                        .HasColumnType("BLOB");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Price")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Exhibits");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "desc1",
                            ExhibitorsId = 1200,
                            Name = "ex1",
                            Price = 200
                        },
                        new
                        {
                            Id = 2,
                            Description = "desc2",
                            ExhibitorsId = 1201,
                            Name = "ex2",
                            Price = 1000
                        },
                        new
                        {
                            Id = 3,
                            Description = "desc3",
                            ExhibitorsId = 1202,
                            Name = "ex3",
                            Price = 2500
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
